import Dispatch
import Foundation

public enum HttpMethod: String, Sendable {
    case get
    case post
    case put
    case delete
}

/// Queue priority for queue-backed model requests.
public enum QueuePriority: String, Sendable {
    case low
    case normal
}

/// Controls the CDN lifecycle for files generated by a request.
public struct FalObjectLifecyclePreference: Equatable, Sendable {
    /// The number of seconds generated files should remain available.
    public let expirationDuration: TimeInterval

    /// Creates a generated-file lifecycle preference.
    /// - Parameter expirationDuration: The number of seconds generated files should remain available.
    public init(expirationDuration: TimeInterval) {
        self.expirationDuration = expirationDuration
    }
}

public protocol RequestOptions {
    var httpMethod: HttpMethod { get }
    var path: String { get }
}

public struct RunOptions: RequestOptions, Sendable {
    public let path: String
    public let httpMethod: HttpMethod
    /// The timeout interval for the HTTP request in seconds. Defaults to 60 seconds.
    public let timeoutInterval: TimeInterval
    /// Additional HTTP headers to include with the request.
    public let headers: [String: String]
    /// Server-side time-to-start deadline in seconds.
    public let startTimeout: TimeInterval?
    /// Routing hint for sticky runner selection.
    public let hint: String?
    /// Queue priority for submit requests.
    public let queuePriority: QueuePriority?
    /// Whether queue-level automatic retries should be disabled for this request.
    public let isRetryDisabled: Bool
    /// Whether fal should store request and response JSON payloads.
    public let storesInputOutput: Bool?
    /// CDN lifecycle preference for generated files.
    public let objectLifecyclePreference: FalObjectLifecyclePreference?
    /// Whether model fallback routing should be disabled for this request.
    public let isFallbackDisabled: Bool

    /// Creates request options with the specified parameters.
    /// - Parameters:
    ///   - path: The path to append to the endpoint URL.
    ///   - httpMethod: The HTTP method to use.
    ///   - timeoutInterval: The timeout interval for the request in seconds. Defaults to 60.
    ///   - headers: Additional HTTP headers to include with the request.
    ///   - startTimeout: Server-side time-to-start deadline in seconds.
    ///   - hint: Routing hint for sticky runner selection.
    ///   - queuePriority: Queue priority for submit requests.
    ///   - disableRetries: Whether queue-level automatic retries should be disabled for this request.
    ///   - storeInputOutput: Whether fal should store request and response JSON payloads.
    ///   - objectLifecyclePreference: CDN lifecycle preference for generated files.
    ///   - disableFallback: Whether model fallback routing should be disabled for this request.
    public init(
        path: String = "",
        httpMethod: HttpMethod = .post,
        timeoutInterval: TimeInterval = 60,
        headers: [String: String] = [:],
        startTimeout: TimeInterval? = nil,
        hint: String? = nil,
        queuePriority: QueuePriority? = nil,
        disableRetries: Bool = false,
        storeInputOutput: Bool? = nil,
        objectLifecyclePreference: FalObjectLifecyclePreference? = nil,
        disableFallback: Bool = false
    ) {
        self.path = path
        self.httpMethod = httpMethod
        self.timeoutInterval = timeoutInterval
        self.headers = headers
        self.startTimeout = startTimeout
        self.hint = hint
        self.queuePriority = queuePriority
        self.isRetryDisabled = disableRetries
        self.storesInputOutput = storeInputOutput
        self.objectLifecyclePreference = objectLifecyclePreference
        self.isFallbackDisabled = disableFallback
    }

    public static func withMethod(
        _ method: HttpMethod,
        headers: [String: String] = [:],
        startTimeout: TimeInterval? = nil,
        hint: String? = nil,
        queuePriority: QueuePriority? = nil,
        disableRetries: Bool = false,
        storeInputOutput: Bool? = nil,
        objectLifecyclePreference: FalObjectLifecyclePreference? = nil,
        disableFallback: Bool = false
    ) -> RunOptions {
        RunOptions(
            path: "",
            httpMethod: method,
            headers: headers,
            startTimeout: startTimeout,
            hint: hint,
            queuePriority: queuePriority,
            disableRetries: disableRetries,
            storeInputOutput: storeInputOutput,
            objectLifecyclePreference: objectLifecyclePreference,
            disableFallback: disableFallback
        )
    }

    public static func withTimeout(
        _ timeout: TimeInterval,
        method: HttpMethod = .post,
        headers: [String: String] = [:],
        startTimeout: TimeInterval? = nil,
        hint: String? = nil,
        queuePriority: QueuePriority? = nil,
        disableRetries: Bool = false,
        storeInputOutput: Bool? = nil,
        objectLifecyclePreference: FalObjectLifecyclePreference? = nil,
        disableFallback: Bool = false
    ) -> RunOptions {
        RunOptions(
            path: "",
            httpMethod: method,
            timeoutInterval: timeout,
            headers: headers,
            startTimeout: startTimeout,
            hint: hint,
            queuePriority: queuePriority,
            disableRetries: disableRetries,
            storeInputOutput: storeInputOutput,
            objectLifecyclePreference: objectLifecyclePreference,
            disableFallback: disableFallback
        )
    }

    public static func route(
        _ path: String,
        withMethod method: HttpMethod = .post,
        headers: [String: String] = [:],
        startTimeout: TimeInterval? = nil,
        hint: String? = nil,
        queuePriority: QueuePriority? = nil,
        disableRetries: Bool = false,
        storeInputOutput: Bool? = nil,
        objectLifecyclePreference: FalObjectLifecyclePreference? = nil,
        disableFallback: Bool = false
    ) -> RunOptions {
        RunOptions(
            path: path,
            httpMethod: method,
            headers: headers,
            startTimeout: startTimeout,
            hint: hint,
            queuePriority: queuePriority,
            disableRetries: disableRetries,
            storeInputOutput: storeInputOutput,
            objectLifecyclePreference: objectLifecyclePreference,
            disableFallback: disableFallback
        )
    }
}

public let DefaultRunOptions: RunOptions = .withMethod(.post)

public typealias OnQueueUpdate = (QueueStatus) -> Void
public typealias OnQueueStatusDetailUpdate = (QueueStatusDetail) -> Void
public typealias OnQueueEnqueue = (QueueSubmitResult) -> Void

public protocol Client {
    var config: ClientConfig { get }

    var queue: Queue { get }

    var realtime: Realtime { get }

    var storage: Storage { get }

    func run(_ id: String, input: Payload?, options: RunOptions) async throws -> Payload

    @available(*, deprecated, message: "Pass the path as part of the app identifier instead")
    func subscribe(
        to app: String,
        path: String?,
        input: Payload?,
        pollInterval: DispatchTimeInterval,
        timeout: DispatchTimeInterval,
        includeLogs: Bool,
        onQueueUpdate: OnQueueUpdate?
    ) async throws -> Payload

    func subscribe(
        to app: String,
        input: Payload?,
        pollInterval: DispatchTimeInterval,
        timeout: DispatchTimeInterval,
        includeLogs: Bool,
        onQueueUpdate: OnQueueUpdate?
    ) async throws -> Payload
}

public extension Client {
    /// Sends a request to the given [id], an optional [path]. This method
    /// is a direct request to the model API and it waits for the processing
    /// to complete before returning the result.
    ///
    /// This is useful for short running requests, but it's not recommended for
    /// long running requests, for those see [submit].
    ///
    /// - Parameters:
    ///   - app: The id of the model app.
    ///   - input: The input to the model.
    ///   - options: The request options.
    func run(_ app: String, input: Payload? = nil, options: RunOptions = DefaultRunOptions) async throws -> Payload {
        try await run(app, input: input, options: options)
    }

    /// Submits a request to the given [app]. This method uses the [queue] API
    /// to submit the request and poll for the result.
    ///
    /// This is useful for long running requests, and it's the preffered way
    /// to interact with the model APIs.
    ///
    /// - Parameters:
    ///   - app: The id of the model app.
    ///   - input: The input to the model.
    ///   - pollInterval: The interval to poll for the result. Defaults to 1 second.
    ///   - timeout: The timeout to wait for the result. Defaults to 3 minutes.
    ///   - includeLogs: Whether to include logs in the result. Defaults to false.
    ///   - onQueueUpdate: A callback to be called when the queue status is updated.
    func subscribe(
        to app: String,
        input: Payload? = nil,
        options: RunOptions,
        pollInterval: DispatchTimeInterval = .seconds(1),
        timeout: DispatchTimeInterval = .minutes(3),
        includeLogs: Bool = false,
        onQueueUpdate: OnQueueUpdate? = nil
    ) async throws -> Payload {
        let requestId = try await queue.submit(app, input: input, options: options)
        try await pollQueueUntilCompleted(
            queue: queue,
            app: app,
            requestId: requestId,
            pollInterval: pollInterval,
            timeout: timeout,
            includeLogs: includeLogs,
            onQueueUpdate: onQueueUpdate
        )
        return try await queue.response(app, of: requestId)
    }

    func subscribe(
        to app: String,
        input: Payload? = nil,
        options: RunOptions,
        pollInterval: DispatchTimeInterval = .seconds(1),
        timeout: DispatchTimeInterval = .minutes(3),
        includeLogs: Bool = false,
        onEnqueue: @escaping OnQueueEnqueue,
        onQueueUpdate: OnQueueUpdate? = nil
    ) async throws -> Payload {
        let submitResult = try await queue.submitDetailed(app, input: input, options: options)
        onEnqueue(submitResult)
        try await pollQueueUntilCompleted(
            queue: queue,
            app: app,
            requestId: submitResult.requestId,
            pollInterval: pollInterval,
            timeout: timeout,
            includeLogs: includeLogs,
            onQueueUpdate: onQueueUpdate
        )
        return try await queue.response(app, of: submitResult.requestId)
    }

    /// Submits a request to the given app and polls for detailed queue status metadata.
    ///
    /// Use this overload when callers need Fal's request metadata, such as request URLs,
    /// metrics, or provider error details, while still using the high-level subscribe flow.
    func subscribeWithStatusDetails(
        to app: String,
        input: Payload? = nil,
        options: RunOptions,
        pollInterval: DispatchTimeInterval = .seconds(1),
        timeout: DispatchTimeInterval = .minutes(3),
        includeLogs: Bool = false,
        onQueueStatusDetailUpdate: @escaping OnQueueStatusDetailUpdate
    ) async throws -> Payload {
        let requestId = try await queue.submit(app, input: input, options: options)
        try await pollQueueUntilCompletedWithStatusDetails(
            queue: queue,
            app: app,
            requestId: requestId,
            pollInterval: pollInterval,
            timeout: timeout,
            includeLogs: includeLogs,
            onQueueStatusDetailUpdate: onQueueStatusDetailUpdate
        )
        return try await queue.response(app, of: requestId)
    }

    func subscribe(
        to app: String,
        input: Payload? = nil,
        pollInterval: DispatchTimeInterval = .seconds(1),
        timeout: DispatchTimeInterval = .minutes(3),
        includeLogs: Bool = false,
        onQueueUpdate: OnQueueUpdate? = nil
    ) async throws -> Payload {
        try await subscribe(to: app,
                            input: input,
                            pollInterval: pollInterval,
                            timeout: timeout,
                            includeLogs: includeLogs,
                            onQueueUpdate: onQueueUpdate)
    }

    func subscribe(
        to app: String,
        input: Payload? = nil,
        pollInterval: DispatchTimeInterval = .seconds(1),
        timeout: DispatchTimeInterval = .minutes(3),
        includeLogs: Bool = false,
        onEnqueue: @escaping OnQueueEnqueue,
        onQueueUpdate: OnQueueUpdate? = nil
    ) async throws -> Payload {
        let submitResult = try await queue.submitDetailed(app, input: input)
        onEnqueue(submitResult)
        try await pollQueueUntilCompleted(
            queue: queue,
            app: app,
            requestId: submitResult.requestId,
            pollInterval: pollInterval,
            timeout: timeout,
            includeLogs: includeLogs,
            onQueueUpdate: onQueueUpdate
        )
        return try await queue.response(app, of: submitResult.requestId)
    }

    /// Submits a request to the given app and polls for detailed queue status metadata.
    ///
    /// Use this overload when callers need Fal's request metadata, such as request URLs,
    /// metrics, or provider error details, while still using the high-level subscribe flow.
    func subscribeWithStatusDetails(
        to app: String,
        input: Payload? = nil,
        pollInterval: DispatchTimeInterval = .seconds(1),
        timeout: DispatchTimeInterval = .minutes(3),
        includeLogs: Bool = false,
        onQueueStatusDetailUpdate: @escaping OnQueueStatusDetailUpdate
    ) async throws -> Payload {
        let requestId = try await queue.submit(app, input: input)
        try await pollQueueUntilCompletedWithStatusDetails(
            queue: queue,
            app: app,
            requestId: requestId,
            pollInterval: pollInterval,
            timeout: timeout,
            includeLogs: includeLogs,
            onQueueStatusDetailUpdate: onQueueStatusDetailUpdate
        )
        return try await queue.response(app, of: requestId)
    }

    @available(*, deprecated, message: "Pass the path as part of the app identifier instead")
    func subscribe(
        to app: String,
        path: String? = nil,
        input: Payload? = nil,
        pollInterval: DispatchTimeInterval = .seconds(1),
        timeout: DispatchTimeInterval = .minutes(3),
        includeLogs: Bool = false,
        onQueueUpdate: OnQueueUpdate? = nil
    ) async throws -> Payload {
        let appId = path.map { "\(app)\($0)" } ?? app
        return try await subscribe(to: appId,
                                   input: input,
                                   pollInterval: pollInterval,
                                   timeout: timeout,
                                   includeLogs: includeLogs,
                                   onQueueUpdate: onQueueUpdate)
    }
}
